### ISSUE TITLE
Change variant type to archlinux

### ISSUE THREAD

**Issue by dennis1248** [manjaro/arkdep-variants#10]
Arkdep uses the build type to identify which method of image build it should utilize. It refers to a distro family, not a specific distro.

This change does nothing other than break compatibility with upstream Arkdep, the archlinux type and manjaro type are identical except for in name.

This will also require this change to be pushed to the Arkdep package in the Manjaro ALPM repos, it is patched to replace the archlinux type with manjaro.

https://github.com/manjaro/arkdep-profiles/blob/main/arkdep-build.d/test-manjaro-gnome/type
https://github.com/manjaro/arkdep-profiles/blob/main/arkdep-build.d/test-manjaro-cosmic/type
https://github.com/manjaro/arkdep-profiles/blob/main/arkdep-build.d/test-manjaro-kde/type
https://github.com/manjaro/arkdep-profiles/blob/main/arkdep-build.d/test-manjaro-xfce/type

**Comment by romangg** [comment]
Can you explain what exactly needs to be pushed to alpm repos?

**Comment by dennis1248** [comment]
A version of Arkdep which does not patch the `archlinux` variant to instead be called `manjaro`.

So just 1:1 what is upstream.

**Comment by philmmanjaro** [comment]
@romangg we are talking about this patch: https://github.com/philmmanjaro/arkdep/commit/c9f0213af932be53bfba3dbbb46a67dda3a23972

**Comment by dennis1248** [comment]
https://github.com/philmmanjaro/arkdep/commit/c9f0213af932be53bfba3dbbb46a67dda3a23972#diff-ee8cc217a5559b5e3bb19f3645345310b661418271f5455b9eed932e45ef1b46R157

This line specifically.
