### ISSUE TITLE
Generic profile cleanup

### ISSUE THREAD

**Issue by dennis1248** [manjaro/arkdep-variants#3]
There is still junk left in the profiles which should be cleaned .

Some examples;
- Dead systemd services.
- Arkane specific tweaks, eg. dconf.
- Some systemd tweaks, which do not work as intended.

**Comment by philmmanjaro** [comment]
It was a quick and dirty copy paste job to get it initially working. I think it is best to remove Arkane specific tweaks first and then we can control which other things are broken when running the system.
