### ISSUE TITLE
GNOME theming

### ISSUE THREAD

**Issue by dennis1248** [manjaro/arkdep-variants#4]
We should decide on how to theme and configure the GNOME images.

https://github.com/manjaro/arkdep-profiles/commit/01764d354bea232a8b45ba4c1a8403f9a334d978 and https://github.com/manjaro/arkdep-profiles/commit/78eebb07ba61e51288de28f7a1ee99a17d8cb183 already implemented the initial recommendation by the Manjaro GNOME maintainers.

The recommendation by the Manjaro GNOME maintainers for the immutable was to avoid anything which may break, such as extensions and GTK theming. Thus GNOME is shipping mostly stock.

Right now the following is implemented;
- Noto Sans 11 font for UI
- Hack 11 font for monospace
- Sans 11 for documents
- Manjaro "abstract" wallpaper as default
- Papirus-Dark-Maia for icons

We should;
- [ ] Ensure all typical Manjaro theming which fits the above description is implemented.
- [ ] Consider if we wish to do any immutable specific customizations such as a custom wallpaper.

**Comment by philmmanjaro** [comment]
Check with Mark and Stefano in our dedicated developer Matrix chat for GNOME related topics. Don't think that another wallpaper to state it is the immutable version is needed, though.

**Comment by yochananmarqos** [comment]
Using Papirus-Dark-Maia doesn't really make much sense if the Maia coloring isn't used for the theme yet. For now, use Papirus-Dark with the default blue.

Hopefully, with GNOME 47 no extension will be required as the color accent feature was finally implemented. I'll be seeing about creating patches to add the Maia coloring. There are several components involved, so it may take some time.

Screenshot from the latest GNOME OS Nightly:

![Screenshot from 2024-08-31 14-08-11](https://github.com/user-attachments/assets/6e3668c9-7f29-44a1-98e4-98815ce864aa)

**Comment by yochananmarqos** [comment]
The Maia accent color is now [implemented](https://gitlab.manjaro.org/release-plan/gnome/-/issues/3). The color can be set with a [gschema override](https://gitlab.manjaro.org/profiles-and-settings/manjaro-gnome-settings/-/blob/bee5c959f5996c55e82cbf3185b32f04eb947ff0/schemas/99_manjaro-settings.gschema.override#L9).
